<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-KGFLCP8" ignored="0" name="Test" tests="1" failures="1" timestamp="27 Sep 2018 10:10:16 GMT" time="125.163" errors="0">
  <testcase name="testA" time="15.807" classname="script.TestDemo">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at script.TestDemo.testA(TestDemo.java:19)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- testA -->
</testsuite> <!-- Test -->
