<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Data:username]]>
    </line>
    <line>
      <![CDATA[Row1]]>
    </line>
    <line>
      <![CDATA[Test:testAis failed @photo is./photo/Thu Sep 27 15_40_10 IST 2018.png]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="125163" started-at="2018-09-27T10:08:09Z" finished-at="2018-09-27T10:10:14Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="125163" started-at="2018-09-27T10:08:09Z" finished-at="2018-09-27T10:10:14Z">
      <class name="script.TestDemo">
        <test-method status="PASS" signature="openApplication(java.lang.String, java.lang.String)[pri:0, instance:script.TestDemo@343f4d3d]" name="openApplication" is-config="true" duration-ms="105121" started-at="2018-09-27T10:08:09Z" finished-at="2018-09-27T10:09:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[localhost]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method status="FAIL" signature="testA()[pri:0, instance:script.TestDemo@343f4d3d]" name="testA" duration-ms="15807" started-at="2018-09-27T10:09:54Z" finished-at="2018-09-27T10:10:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at script.TestDemo.testA(TestDemo.java:19)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Data:username]]>
            </line>
            <line>
              <![CDATA[Row1]]>
            </line>
          </reporter-output>
        </test-method> <!-- testA -->
        <test-method status="PASS" signature="closeApplication(org.testng.ITestResult)[pri:0, instance:script.TestDemo@343f4d3d]" name="closeApplication" is-config="true" duration-ms="3945" started-at="2018-09-27T10:10:10Z" finished-at="2018-09-27T10:10:14Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testA status=FAILURE method=TestDemo.testA()[pri:0, instance:script.TestDemo@343f4d3d] output=Data:username]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[Test:testAis failed @photo is./photo/Thu Sep 27 15_40_10 IST 2018.png]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeApplication -->
      </class> <!-- script.TestDemo -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
